Tickers parsing
andrros3030/fleppa_trade_bot pull request #7
Opened 2023-01-17 18:13 UTC by savageego

2023-01-17 20:02 UTC, andrros3030 commented on src/main.py
> +        result.append(f'EUR: {eur_today} ({eur_change} % ⚪)')
См прошлый комментарий, для каждого ключа в словаре добавляй строку вида {key}: {value} ({change})

2023-01-17 20:02 UTC, andrros3030 commented on src/main.py
> +    bot.send_message(message.chat.id, '\n'.join(result))
классное решение с джойном 👍

2023-01-18 10:59 UTC, savageego commented on src/main.py
> +@bot.message_handler(func=lambda message: message.text.upper() != 'MOEX')
Андрей, хз, где ты это увидел, я у себя не вижу. К тому же я вчера сразу удалил все, что связано с "MOEX"

2023-01-18 12:07 UTC, andrros3030 commented on src/main.py
> +@bot.message_handler(func=lambda message: message.text.upper() != 'MOEX')
Это было до мержа, сейчас всё ок)

2023-01-18 13:42 UTC, andrros3030 requested changes

2023-01-18 13:42 UTC, andrros3030 commented on src/request_currency.py
> +        result.update(
почему update, а не простое присвоение?

2023-01-18 13:53 UTC, savageego commented on src/request_currency.py
> +        result.update(
там же цикл, я добавляю новую информацию в словарь, не удаляя старую, нет?

2023-01-18 14:37 UTC, andrros3030 approved these changes

2023-01-18 14:42 UTC, merged